### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by MrCrazyID** [bosch-ros-pkg/stm32#13]
I'm missing a Licence in the root of the repo, is it possible to add a license?

**Comment by dejanpan** [comment]
Some code is also hijacked from other projects. Let me check with a core developer @yigitgunay, will get back to you by the end of the week.

**Comment by yigitgunay** [comment]
I just committed a LICENSE, which is a BSD 3-clause license.

Notice: The FreeRTOS kernel including its entire modifications is licensed with FreeRTOS open source license: http://www.freertos.org/a00114.html. Code related to STM32, ARM, lwip, and some other code already include their license texts in each file.

In addition to these licenses, the LICENSE in the root directory applies, unless LICENSE contradicts the original license.
